<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<PackageId>ZStack.QingTui</PackageId>
		<Description>ZStack框架 轻推SDK</Description>
		<PackageIcon>qingtui.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="MimeTypesMap" Version="1.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZStack.Core\ZStack.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include=".\qingtui.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectCapability Include="DynamicDependentFile" />
		<ProjectCapability Include="DynamicFileNesting" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.201" />
	</ItemGroup>
	
</Project>
