<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>ZStack.AspNetCore.OpenTelemetry</PackageId>
		<Description>ZStack.AspNetCore框架 OpenTelemetry遥测插件</Description>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
	  <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
	  <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\ZStack.AspNetCore\ZStack.AspNetCore.csproj" />
	</ItemGroup>
</Project>
