<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>ZStack.AspNetCore</PackageId>
		<Description>ZStack.AspNetCore框架</Description>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
		<PackageReference Include="NetEscapades.Configuration.Yaml" Version="3.1.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="1.2.45" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="NewLife.Redis" Version="5.7.2024.801" />
		<PackageReference Include="System.Private.Uri" Version="4.3.2" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Include="YamlDotNet" Version="16.2.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZStack.Extensions\ZStack.Extensions.csproj" />
  </ItemGroup>

</Project>
