<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>ZStack.AspNetCore</PackageId>
		<Description>ZStack.AspNetCore框架</Description>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.13.10" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZStack.Core\ZStack.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.201" />
  </ItemGroup>

</Project>
