<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>ZStack.AspNetCore</PackageId>
		<Description>ZStack.AspNetCore框架</Description>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="NewLife.Redis" Version="5.7.2024.801" />
		<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.3.8" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.0" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZStack.Extensions\ZStack.Extensions.csproj" />
  </ItemGroup>

</Project>
