<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>ZStack.AspNetCore.Hangfire.PostgreSql</PackageId>
		<Description>ZStack.AspNetCore框架Hangfire调度插件【PostgreSql】</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ZStack.AspNetCore.Hangfire\ZStack.AspNetCore.Hangfire.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
	</ItemGroup>

</Project>
