<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>1701;1702;1591;8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\framework\ZStack.AspNetCore.OpenTelemetry\ZStack.AspNetCore.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\framework\ZStack.AspNetCore.SqlSugar\ZStack.AspNetCore.SqlSugar.csproj" />
    <ProjectReference Include="..\..\framework\ZStack.AspNetCore\ZStack.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <!--<PackageReference Include="MySqlConnector" Version="2.4.0" />-->
    <PackageReference Include="Npgsql" Version="9.0.1" />
    <PackageReference Include="Npgsql.OpenTelemetry" Version="9.0.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.10.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="index-mini-profiler.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
