global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using ZStack.AspNetCore;
global using ZStack.AspNetCore.Attributes;
global using ZStack.Core.DependencyInjection;
global using App = ZStack.AspNetCore.App;
