<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591;8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZStack.AspNetCore" Version="10.9.0" />
    <!--#if (components == eventbus) -->
    <PackageReference Include="ZStack.AspNetCore.EventBus" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == hangfire) -->
    <PackageReference Include="ZStack.AspNetCore.Hangfire" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == hangfire && hangfireStorage == memory) -->
    <PackageReference Include="ZStack.AspNetCore.Hangfire.MemoryStorage" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == hangfire && hangfireStorage == redis) -->
    <PackageReference Include="ZStack.AspNetCore.Hangfire.Redis" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == hangfire && hangfireStorage == postgresql) -->
    <PackageReference Include="ZStack.AspNetCore.Hangfire.PostgreSql" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == sqlsugar) -->
    <PackageReference Include="ZStack.AspNetCore.SqlSugar" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == opentelemetry) -->
    <PackageReference Include="ZStack.AspNetCore.OpenTelemetry" Version="10.9.0" />
    <!--#endif -->
    <!--#if (components == qingtui) -->
    <PackageReference Include="ZStack.AspNetCore.QingTui" Version="10.9.0" />
    <!--#endif -->
  </ItemGroup>

  <ItemGroup>
    <None Update="Configuration\**\*.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
