<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SqlSugarCoreNoDrive" Version="5.1.4.216" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\framework\ZStack.AspNetCore.QingTui\ZStack.AspNetCore.QingTui.csproj" />
    <ProjectReference Include="..\..\framework\ZStack.AspNetCore\ZStack.AspNetCore.csproj" />
  </ItemGroup>
	
</Project>
